//go:build linux

// ---
// relationships:
//   verifies: linux-user-service
// ---

package userservice

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderUnitEscapesSystemdSyntaxExactly(t *testing.T) {
	executable := `/opt/sample folder/a"b\c%$d`
	environment := environmentPaths{
		configuration: `/home/sample folder/config"quote\slash%percent$dollar`,
		data:          "/home/sample/data",
		state:         "/home/sample/state",
		runtime:       "/run/user/1000",
	}
	unit, err := renderUnit(executable, environment)
	if err != nil {
		t.Fatalf("renderUnit(): %v", err)
	}
	want := `# Generated by wyrwood. Re-run "wyrwood service install" after moving the executable.
[Unit]
Description=Wyrwood per-user SSH agent proxy

[Service]
Type=simple
Environment="XDG_CONFIG_HOME=/home/sample folder/config\"quote\\slash%%percent$dollar"
Environment="XDG_DATA_HOME=/home/sample/data"
Environment="XDG_STATE_HOME=/home/sample/state"
Environment="XDG_RUNTIME_DIR=/run/user/1000"
ExecStart=:/usr/bin/env -- "/opt/sample folder/a\"b\\c%%$d" daemon
Restart=on-failure
RestartSec=2s
TimeoutStopSec=15s
UMask=0077

[Install]
WantedBy=default.target
`
	if string(unit) != want {
		t.Fatalf("unit bytes:\n%s\nwant:\n%s", unit, want)
	}
	for _, forbidden := range []string{"sudo", "--system", "kardianos"} {
		if strings.Contains(string(unit), forbidden) {
			t.Fatalf("unit contains forbidden value %q", forbidden)
		}
	}
}

func TestRenderUnitRejectsUnsafeExecutablePaths(t *testing.T) {
	for _, path := range []string{"relative", "/tmp/../sample", "/tmp/line\nbreak", "/tmp/line\rbreak", "/tmp/zero\x00byte"} {
		if _, err := renderUnit(path, fixtureEnvironment()); err == nil {
			t.Fatalf("renderUnit(%q) succeeded", path)
		}
	}
}

func TestRenderedUnitPassesLocalSystemdParser(t *testing.T) {
	analyzer, err := exec.LookPath("systemd-analyze")
	if err != nil {
		t.Skip("systemd-analyze is unavailable")
	}
	directory := t.TempDir()
	executable := filepath.Join(directory, `sample space"slash\percent%cash$`)
	if err := os.WriteFile(executable, []byte("fixture"), 0o700); err != nil {
		t.Fatalf("WriteFile(executable): %v", err)
	}
	unit, err := renderUnit(executable, fixtureEnvironment())
	if err != nil {
		t.Fatalf("renderUnit(): %v", err)
	}
	unitPath := filepath.Join(directory, UnitName)
	if err := os.WriteFile(unitPath, unit, unitMode); err != nil {
		t.Fatalf("WriteFile(unit): %v", err)
	}
	command := exec.Command(analyzer, "verify", "--man=no", unitPath)
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("systemd-analyze verify: %v\n%s", err, output)
	}
}

func fixtureEnvironment() environmentPaths {
	return environmentPaths{
		configuration: "/home/sample/.config", data: "/home/sample/.local/share",
		state: "/home/sample/.local/state", runtime: "/run/user/1000",
	}
}
