//go:build linux

// ---
// relationships:
//   implements: linux-user-service
// ---

package userservice

import (
	"errors"
	"path/filepath"
	"strings"
)

const (
	UnitName            = "wyrwood.service"
	unitMode            = 0o600
	environmentLauncher = "/usr/bin/env"
)

func renderUnit(executable string, environment environmentPaths) ([]byte, error) {
	word, err := systemdExecWord(executable)
	if err != nil {
		return nil, err
	}
	configuration, err := systemdEnvironment("XDG_CONFIG_HOME", environment.configuration)
	if err != nil {
		return nil, err
	}
	data, err := systemdEnvironment("XDG_DATA_HOME", environment.data)
	if err != nil {
		return nil, err
	}
	state, err := systemdEnvironment("XDG_STATE_HOME", environment.state)
	if err != nil {
		return nil, err
	}
	runtime, err := systemdEnvironment("XDG_RUNTIME_DIR", environment.runtime)
	if err != nil {
		return nil, err
	}
	return []byte(`# Generated by wyrwood. Re-run "wyrwood service install" after moving the executable.
[Unit]
Description=Wyrwood per-user SSH agent proxy

[Service]
Type=simple
Environment=` + configuration + `
Environment=` + data + `
Environment=` + state + `
Environment=` + runtime + `
ExecStart=:` + environmentLauncher + ` -- ` + word + ` daemon
Restart=on-failure
RestartSec=2s
TimeoutStopSec=15s
UMask=0077

[Install]
WantedBy=default.target
`), nil
}

func systemdEnvironment(name, value string) (string, error) {
	if err := validatePath(value); err != nil {
		return "", err
	}
	replacer := strings.NewReplacer(`\`, `\\`, `"`, `\"`, `%`, `%%`)
	return `"` + name + `=` + replacer.Replace(value) + `"`, nil
}

// systemdExecWord quotes one ExecStart word. The ExecStart colon modifier
// disables dollar-variable expansion; percent specifiers still require doubling.
func systemdExecWord(value string) (string, error) {
	if value == "" || hasUnsafeControl(value) ||
		!filepath.IsAbs(value) || filepath.Clean(value) != value {
		return "", errors.New("service executable path is unsafe")
	}
	replacer := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		`%`, `%%`,
	)
	return `"` + replacer.Replace(value) + `"`, nil
}
